name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "samuel.billaud@mergify.com"
        git config --global user.name "Samuel Billaud"

    - name: Install dependencies
      shell: bash
      run: pnpm install
